package com.kynzai.tictactoe.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFFA63A23)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFFFDAD3)
val light_onPrimaryContainer = Color(0xFF3D0600)
val light_secondary = Color(0xFF77574F)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFFFDAD3)
val light_onSecondaryContainer = Color(0xFF2C1510)
val light_tertiary = Color(0xFF6E5D2E)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFF8E0A6)
val light_onTertiaryContainer = Color(0xFF241A00)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFFFBFF)
val light_onBackground = Color(0xFF201A19)
val light_surface = Color(0xFFFFFBFF)
val light_onSurface = Color(0xFF201A19)
val light_surfaceVariant = Color(0xFFF5DDD9)
val light_onSurfaceVariant = Color(0xFF534340)
val light_outline = Color(0xFF85736F)
val light_inverseOnSurface = Color(0xFFFBEEEB)
val light_inverseSurface = Color(0xFF362F2D)
val light_inversePrimary = Color(0xFFFFB4A4)
val light_shadow = Color(0xFF000000)
val light_surfaceTint = Color(0xFFA63A23)
val light_outlineVariant = Color(0xFFD8C2BD)
val light_scrim = Color(0xFF000000)

val dark_primary = Color(0xFFFFB4A4)
val dark_onPrimary = Color(0xFF630E00)
val dark_primaryContainer = Color(0xFF86220D)
val dark_onPrimaryContainer = Color(0xFFFFDAD3)
val dark_secondary = Color(0xFFE7BDB4)
val dark_onSecondary = Color(0xFF442A24)
val dark_secondaryContainer = Color(0xFF5D3F39)
val dark_onSecondaryContainer = Color(0xFFFFDAD3)
val dark_tertiary = Color(0xFFDBC58C)
val dark_onTertiary = Color(0xFF3C2F04)
val dark_tertiaryContainer = Color(0xFF544519)
val dark_onTertiaryContainer = Color(0xFFF8E0A6)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF201A19)
val dark_onBackground = Color(0xFFEDE0DD)
val dark_surface = Color(0xFF201A19)
val dark_onSurface = Color(0xFFEDE0DD)
val dark_surfaceVariant = Color(0xFF534340)
val dark_onSurfaceVariant = Color(0xFFD8C2BD)
val dark_outline = Color(0xFFA08C88)
val dark_inverseOnSurface = Color(0xFF201A19)
val dark_inverseSurface = Color(0xFFEDE0DD)
val dark_inversePrimary = Color(0xFFA63A23)
val dark_shadow = Color(0xFF000000)
val dark_surfaceTint = Color(0xFFFFB4A4)
val dark_outlineVariant = Color(0xFF534340)
val dark_scrim = Color(0xFF000000)

val seed = Color(0xFFEF6F53)

val light_flirt = Color(0xFFb4007e)
val light_flirtContainer = Color(0xFFffd8e8)
val light_onFlirt = Color(0xFFffffff)
val light_onFlirtContainer = Color(0xFF3d0027)

val dark_flirt = Color(0xFFffafd5)
val dark_flirtContainer = Color(0xFF620042)
val dark_onFlirt = Color(0xFF8a005f)
val dark_onFlirtContainer = Color(0xFFffd8e8)
